{{- if and .Values.ingress.secrets.originTls.data ( or ( eq .Values.deployEnv "prod" ) ( eq .Values.deployEnv "democracy" ) ) }}
apiVersion: v1
kind: Secret
metadata:
  name: origin-tls-{{ .Values.deployEnv }}
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.secrets.originTls.data.cert | b64enc }}
  tls.key: {{ .Values.ingress.secrets.originTls.data.key | b64enc }}
{{- end }}
