# apiVersion: apps/v1
# kind: Deployment
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.deployEnv }}-varnish
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
  annotations: 
    rollout.argoproj.io/revision: "{{ .Release.Revision }}"
spec:
  strategy:
    blueGreen:
      activeService: varnish-{{ .Values.deployEnv }}
      autoPromotionEnabled: true
      prePromotionAnalysis:
        templates:
          # - templateName: rollout-readiness-{{ .Values.deployEnv }}
          - templateName: rollout-ready-{{ .Values.deployEnv }}
        args:
          # - name: rollout-value
          #   value: "{{ .Release.Revision }}"
          # - name: deploy-env
          #   value: "{{ .Values.deployEnv }}"
          - name: healthcheck-hostname
            value: "nginx-{{ .Values.deployEnv }}-{{ .Release.Revision }}"
  selector:
    matchLabels:
      app: varnish-{{ .Values.deployEnv }}
      # releaseRevision: "{{ .Release.Revision }}"
  revisionHistoryLimit: 2
  replicas: {{ .Values.varnish.replicaCount }}
  template:
    metadata:
      labels:
        app: varnish-{{ .Values.deployEnv }}
        tier: application-{{ .Values.deployEnv }}
        deployEnv: "{{ .Values.deployEnv }}"
        stackRole: varnish
        releaseRevision: "{{ .Release.Revision }}"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mongo
            topologyKey: kubernetes.io.hostname
        nodeAffinity:
          {{- include "sefaria.nodeAffinities" . | nindent 10 }}
      containers:
      - name: varnish
        image: "{{ .Values.varnish.containerImage.imageRegistry }}:{{ .Values.varnish.containerImage.tag }}"
        imagePullPolicy: Always
        args:
          - -F
          - -f 
          - /etc/varnish/sefaria.vcl
          - -S
          - /etc/varnish-secret/secret
          - -T
          - 0.0.0.0:6082
          - -p
          - between_bytes_timeout={{ .Values.varnish.tuning.between_bytes_timeout }}
          - -p
          - first_byte_timeout={{ .Values.varnish.tuning.first_byte_timeout }}
          - -p
          - nuke_limit={{ .Values.varnish.tuning.nuke_limit }}
          - -p
          - thread_pool_max={{ .Values.varnish.tuning.thread_pool_max }}
          - -s
          - malloc,{{ .Values.varnish.tuning.malloc }}
        ports:
        - containerPort: 8040
        - containerPort: 6082
        resources: {{ toYaml .Values.varnish.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /varnish-secret
          name: varnish-secret
          readOnly: true
        - mountPath: /etc/varnish/
          name: varnish-config
          readOnly: true
      volumes:
        - name: varnish-secret
          secret:
            secretName: {{ template "sefaria.secrets.varnish" . }}
        - name:  varnish-config
          configMap:
            name: {{ .Values.deployEnv }}-varnish-config
