{{- if ne .Values.sandbox "true" }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.deployEnv }}-webpage
  labels:
    {{- include "sefaria.labels" . | nindent 4 }}
spec:
  schedule: "13 6 * * 2"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: webpage-cronjob
            image: "{{ .Values.web.containerImage.imageRegistry }}:{{ .Values.web.containerImage.tag }}"
            env:
            - name: TRELLO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: { { template "sefaria.secrets.webpageCronjob" . } }
                  key: TRELLO_TOKEN
            - name: TRELLO_KEY
              valueFrom:
                secretKeyRef:
                  name: { { template "sefaria.secrets.webpageCronjob" . } }
                  key: TRELLO_KEY
            - name: BOARD_ID
              valueFrom:
                secretKeyRef:
                  name: { { template "sefaria.secrets.webpageCronjob" . } }
                  key: BOARD_ID
            - name: SLACK_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "sefaria.secrets.slackWebhook" . }}
                  key: slack-webhook
            envFrom:
            - secretRef:
                name: {{ .Values.secrets.localSettings.ref }}
                optional: true
            - secretRef:
                name: local-settings-secrets-{{ .Values.deployEnv }}
                optional: true
            - configMapRef:
                name: local-settings-{{ .Values.deployEnv }}
            volumeMounts:
              - mountPath: /app/sefaria/local_settings.py
                name: local-settings
                subPath: local_settings.py
                readOnly: true
            command: ["bash"]
            args: [
              "-c",
              "/app/run /app/scripts/webpage_cronjob.py weekly"
            ]
          restartPolicy: Never
          volumes:
          - name: local-settings
            configMap:
              name: local-settings-file-{{ .Values.deployEnv }}
              items:
                - key: local_settings.py
                  path: local_settings.py
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
{{- end }}


