---
deployEnv: testing
releaseImageTag: asdf
dafChat:
  rtc:
    containerImage: defaultImage
    replicaCount: 1
    resources:
      request:
        memory: "100Mi"
        cpu: "50m"
      limit:
        memory: "250Mi"
        cpu: "150m"
    env:
      TURN_SERVER: dummyValue
      TURN_USER: dummyValue
      TURN_PW: dummyValue
  coturn:
    containerImage: defaultImage
    replicaCount: 1
    resources:
      request:
        memory: "100Mi"
        cpu: "50m"
      limit:
        memory: "250Mi"
        cpu: "150m"
    env:
      TURN_SECRET: dummyValue
      TURN_USER: dummyValue
      TURN_REALM: dummyValue
...
