apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.deployEnv }}
  annotations:
    {{- if eq .Values.sandbox "true" }}
    kubernetes.io/ingress.class: nginx-ingress
    {{- else }}
    kubernetes.io/ingress.global-static-ip-name: "sefaria-{{ .Values.deployEnv }}"
    {{- end }}
spec:
  tls:
    - secretName: {{ template "secrets.originTls" . }}
    - secretName: {{ template "secrets.originIlTls" . }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ tpl .host . | quote }}
      http:
        paths:
          - path: {{ .path | default "/*" | quote }}
            backend:
              serviceName: {{ .serviceName | default "nginx" }}-{{ .Values.deployEnv }}
              servicePort: {{ .port | default "80" }}
    {{- end }}
---
{{- if and .Values.ingress.secrets.originTls.cert.data .Values.ingress.secrets.originTls.key.data ( or ( eq .Values.deployEnv "prod" ) ( eq .Values.deployEnv "democracy" ) ) }}
apiVersion: v1
kind: Secret
metadata:
  name: origin-tls-{{ .Values.deployEnv }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.secrets.originTls.cert.data | b64enc }}
  tls.key: {{ .Values.ingress.secrets.originTls.key.data | b64enc }}
{{- end }}
---
{{- if and .Values.ingress.secrets.originIlTls.cert.data .Values.ingress.secrets.originIlTls.key.data ( eq .Values.deployEnv "prod" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: origin-il-tls-{{ .Values.deployEnv }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.secrets.originIlTls.cert.data | b64enc }}
  tls.key: {{ .Values.ingress.secrets.originIlTls.key.data | b64enc }}
{{- end }}

