---
apiVersion: v1
kind: Secret
metadata:
  name: local-settings-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  local_settings.py: {{ .Files.Get "local_settings.py" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: google-client-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  client_secrets.json: {{ .Files.Get "secrets/client_secrets.json" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: varnish-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  varnish-secret: {{ .Files.Get "secrets/varnish-secret" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: school-lookup-data-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  schools.tsv: {{ .Files.Get "secrets/schools.tsv" | b64enc }}    
---
apiVersion: v1
kind: Secret
metadata: 
  name: backup-manager-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  BackupManagerKey.json: {{ .Files.Get "secrets/BackupManagerKey.json" | b64enc }}
  gcloud-service-accnt.json: {{ .Files.Get "secrets/gcloud-service-accnt.json" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata: 
  name: logging-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  {{ if eq (substr 0 4 .Values.deployEnv) "prod" }}
  logging-secret.json: {{ .Files.Get "secrets/logging-secret.prod.json" | b64enc }}
  {{ else }}
  logging-secret.json: {{ .Files.Get "secrets/logging-secret.dev.json" | b64enc }}
  {{ end }}
---