---
{{- if .Values.secrets.localSettings.DATABASES_HOST.data }}
apiVersion: v1
kind: Secret
metadata:
  name: local-settings-secrets-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  DATABASES_HOST: {{ .Values.secrets.localSettings.DATABASES_HOST.data | b64enc }}
  DATABASES_PASS: {{ .Values.secrets.localSettings.DATABASES_PASS.data | b64enc }}
  DATABASES_USER: {{ .Values.secrets.localSettings.DATABASES_USER.data | b64enc }}
  DATABASES_PORT: {{ .Values.secrets.localSettings.DATABASES_PORT.data | b64enc }}
  GOOGLE_OAUTH2_CLIENT_ID: {{ .Values.secrets.localSettings.GOOGLE_OAUTH2_CLIENT_ID.data | b64enc }}
  GOOGLE_OAUTH2_CLIENT_SECRET: {{ .Values.secrets.localSettings.GOOGLE_OAUTH2_CLIENT_SECRET.data | b64enc }}
  SECRET_KEY: {{ .Values.secrets.localSettings.SECRET_KEY.data | b64enc }}
  MANDRILL_API_KEY: {{ .Values.secrets.localSettings.MANDRILL_API_KEY.data | b64enc }}
  SEFARIA_DB: {{ .Values.secrets.localSettings.SEFARIA_DB.data | b64enc }}
  SEFARIA_DB_USER: {{ .Values.secrets.localSettings.SEFARIA_DB_USER.data | b64enc }}
  SEFARIA_DB_PASSWORD: {{ .Values.secrets.localSettings.SEFARIA_DB_PASSWORD.data | b64enc }}
  SEARCH_ADMIN_USER: {{ .Values.secrets.localSettings.SEARCH_ADMIN_USER.data | b64enc }}
  SEARCH_ADMIN_PW: {{ .Values.secrets.localSettings.SEARCH_ADMIN_PW.data | b64enc }}
  SEARCH_ADMIN_K8S: {{ .Values.secrets.localSettings.SEARCH_ADMIN_K8S.data | b64enc }}
  TURN_SECRET: {{ .Values.secrets.localSettings.TURN_SECRET.data | b64enc }}
  TURN_USER: {{ .Values.secrets.localSettings.TURN_USER.data | b64enc }}
  SEFARIA_BOT_API_KEY: {{ .Values.secrets.localSettings.SEFARIA_BOT_API_KEY.data | b64enc }}
  CLOUDFLARE_ZONE: {{ .Values.secrets.localSettings.CLOUDFLARE_ZONE.data | b64enc }}
  CLOUDFLARE_EMAIL: {{ .Values.secrets.localSettings.CLOUDFLARE_EMAIL.data | b64enc }}
  CLOUDFLARE_TOKEN: {{ .Values.secrets.localSettings.CLOUDFLARE_TOKEN.data | b64enc }}
  GOOGLE_TAG_MANAGER_CODE: {{ .Values.secrets.localSettings.GOOGLE_TAG_MANAGER_CODE.data | b64enc }}
  GOOGLE_ANALYTICS_CODE: {{ .Values.secrets.localSettings.GOOGLE_ANALYTICS_CODE.data | b64enc }}
  GOOGLE_MAPS_API_KEY: {{ .Values.secrets.localSettings.GOOGLE_MAPS_API_KEY.data | b64enc }}
  MIXPANEL_CODE: {{ .Values.secrets.localSettings.MIXPANEL_CODE.data | b64enc }}
  HOTJAR_ID: {{ .Values.secrets.localSettings.HOTJAR_ID.data | b64enc }}
  AWS_ACCESS_KEY: {{ .Values.secrets.localSettings.AWS_ACCESS_KEY.data | b64enc }}
  AWS_SECRET_KEY: {{ .Values.secrets.localSettings.AWS_SECRET_KEY.data | b64enc }}
  S3_BUCKET: {{ .Values.secrets.localSettings.S3_BUCKET.data | b64enc }}
  NATIONBUILDER_TOKEN: {{ .Values.secrets.localSettings.NATIONBUILDER_TOKEN.data | b64enc }}
  NATIONBUILDER_CLIENT_ID: {{ .Values.secrets.localSettings.NATIONBUILDER_CLIENT_ID.data | b64enc }}
  NATIONBUILDER_CLIENT_SECRET: {{ .Values.secrets.localSettings.NATIONBUILDER_CLIENT_SECRET.data | b64enc }}
  MAILCHIMP_API_KEY: {{ .Values.secrets.localSettings.MAILCHIMP_API_KEY.data | b64enc }}
  MAILCHIMP_ANNOUNCE_ID: {{ .Values.secrets.localSettings.MAILCHIMP_ANNOUNCE_ID.data | b64enc }}
  MAILCHIMP_WEBHOOK_KEY: {{ .Values.secrets.localSettings.MAILCHIMP_WEBHOOK_KEY.data | b64enc }}
  RECAPTCHA_PUBLIC_KEY: {{ .Values.secrets.localSettings.RECAPTCHA_PUBLIC_KEY.data | b64enc }}
  RECAPTCHA_PRIVATE_KEY: {{ .Values.secrets.localSettings.RECAPTCHA_PRIVATE_KEY.data | b64enc }}
  SIMPLE_JWT_SIGNING_KEY: {{ .Values.secrets.localSettings.SIMPLE_JWT_SIGNING_KEY.data | b64enc }}
  MOBILE_APP_KEY: {{ .Values.secrets.localSettings.MOBILE_APP_KEY.data | b64enc }}
{{- end }}
---
{{- if .Values.web.secrets.googleClient.data }}
apiVersion: v1
kind: Secret
metadata:
  name: google-client-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  client_secrets.json: {{ .Values.web.secrets.googleClient.data | b64enc }}
{{- end }}
---
{{- if .Values.varnish.secrets.varnish.data }}
apiVersion: v1
kind: Secret
metadata:
  name: varnish-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  varnish-secret: {{ .Values.varnish.secrets.varnish.data | b64enc }}
{{- end }}
---
{{- if .Values.web.secrets.schoolLookup.data }}
apiVersion: v1
kind: Secret
metadata:
  name: school-lookup-data-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  schools.tsv: {{ .Values.web.secrets.schoolLookup.data | b64enc }}
{{- end }}
---
{{- if and .Values.secrets.backupManager.key.data .Values.secrets.backupManager.serviceAccount.data }}
apiVersion: v1
kind: Secret
metadata: 
  name: backup-manager-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  BackupManagerKey.json: {{ .Values.secrets.backupManager.key.data | b64enc }}
  gcloud-service-accnt.json: {{ .Values.secrets.backupManager.serviceAccount.data | b64enc }}
{{- end }}
---
{{- if .Values.web.secrets.logging.data }}
apiVersion: v1
kind: Secret
metadata: 
  name: logging-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  logging-secret.json: {{ .Values.web.secrets.logging.data | b64enc }}
{{- end }}
---
{{- if .Values.secrets.slackWebhook.data }}
apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  slack-webhook: {{ .Values.secrets.slackWebhook.data | b64enc | quote }}
{{- end }}
---
