---
apiVersion: v1
kind: Secret
metadata:
  name: local-settings-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  local_settings.py: {{ .Files.Get "local_settings.py" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: google-client-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  client_secrets.json: {{ .Files.Get "secrets/client_secrets.json" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: varnish-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  varnish-secret: {{ .Files.Get "secrets/varnish-secret" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: school-lookup-data-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  schools.tsv: {{ .Files.Get "secrets/schools.tsv" | b64enc }}    
---
apiVersion: v1
kind: Secret
metadata: 
  name: backup-manager-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  BackupManagerKey.json: {{ .Files.Get "secrets/BackupManagerKey.json" | b64enc }}
  gcloud-service-accnt.json: {{ .Files.Get "secrets/gcloud-service-accnt.json" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata: 
  name: logging-secret-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  {{ if eq (substr 0 4 .Values.deployEnv) "prod" }}
  logging-secret.json: {{ .Files.Get "secrets/logging-secret.prod.json" | b64enc }}
  {{ else }}
  logging-secret.json: {{ .Files.Get "secrets/logging-secret.dev.json" | b64enc }}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-conf-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  nginx.template.conf: {{ .Files.Get "nginx.template.conf" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
type: Opaque
data:
  slack-webhook: {{ "https://hooks.slack.com/services/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" | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gunicorn-config-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
  namespace: default
data: 
  gunicorn.conf.py: {{ .Files.Get "gunicorn.conf.py" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata: 
  name: robots-txt-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
  namespace: default
data:
  robots.txt: {{ .Files.Get "robots.txt" | b64enc }}
...