---
deployEnv: ${DEPLOY_ENV}
releaseImageTag: ${IMAGE_TAG}
dafChat:
  sefariaHost: ${SEFARIA_HOST}
  auth:
    turnUser: ${TURN_USER}
    turnSecret: ${TURN_SECRET}
  rtc: 
    containerImage: ${IMAGE_NAME_RTC}
  coturn:
    containerImage: ${IMAGE_NAME_COTURN}
...
