on:
  pull_request:
    paths:
      - "helm-chart/**"

jobs:
  helm-tests:
    name: "Helm Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0
      - name: Lint chart
        run: ct lint --charts .
