name: Helm Release

on:
  push:
    branches:
      - master

jobs:

  changes:
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    runs-on: ubuntu-latest
    if: |
      (github.repository == 'sefaria/sefaria-project')
    outputs:
      charts: ${{ steps.filter.outputs.charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            charts:
              - 'helm-chart/**/*'
  semantic-release:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: |
      (github.repository == 'sefaria/sefaria-project') && (needs.changes.outputs.charts == 'true')
    outputs:
      release-version: ${{ steps.semantic.outputs.release-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          working_directory: ./helm-chart
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  chart:
    name: Release Chart
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to write releases
    needs:
      - changes
      - semantic-release
    if: |
      (github.repository == 'sefaria/sefaria-project') && (needs.changes.outputs.charts == 'true')
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          # Fetch entire history. Required for chart-releaser; see https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
          fetch-depth: 0
      - name: Setup
        shell: bash
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Get appVersion
        id: appVersion
        run: |
          echo '::set-output name=appVersion::$(git describe --match "v*" --abbrev=0 HEAD --tags)'
      - name: Download yq
        run: |
          wget -nv -nc -O yq https://github.com/mikefarah/yq/releases/download/v4.20.2/yq_linux_amd64
          chmod +x yq
      - name: Update chart version
        run: ./yq -i e '.version = "${{ needs.semantic-release.outputs.release-version }}"' helm-chart/sefaria-project/Chart.yaml
      - name: Update chart appVersion
        run: ./yq -i e '.appVersion = "${{ steps.appVersion.outputs.appVersion }}"' helm-chart/sefaria-project/Chart.yaml
      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_SKIP_EXISTING: "false"
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "helm-chart-{{ .Version }}"
        with:
          charts_dir: helm-chart
