name: Image builder
on:
  push:
    branches:
      - *

jobs:
  build-generic:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ web, node ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.DEV_CLOUDBUILD_SA_KEY }}
      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DEV_PROJECT }}/sefaria-${{ matrix.app }}-${{ GITHUB_REF_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,patter={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          flavour: |
            latest=true
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry, ref=sefaria-${{ matrix.app }}/cache
          cache-to: type=registry, ref=sefaria-${{ matrix.app }}/cache, mode=max
          context: .
          push: true
          file: build/${{ matrix.app }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  build-asset:
    runs-on: ubuntu-latest
    needs: build-generic
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.DEV_CLOUDBUILD_SA_KEY }}
      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DEV_PROJECT }}/sefaria-asset-${{ GITHUB_REF_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,patter={{raw}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          flavour: |
            latest=true
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry, ref=sefaria-asset/cache
          cache-to: type=registry, ref=sefaria-asset/cache, mode=max
          context: .
          push: true
          build-args:
            - SRC_IMG=gcr.io/${{ secrets.DEV_PROJECT }}/sefaria-web-${{ GITHUB_REF_NAME }}:${{ GITHUB_SHA }}
          file: build/nginx/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
