
# this will only handle static python and js tests

# Remove "continue-on-error" once we work out all the kinks
---
name: static-tests
on:
  - push
jobs:
  jest-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
          npm run build-prod
      - name: Run Jest Tests
        run: npm run jest-travis
        continue-on-error: true

  py-tests:
    # Requires an active mongodb connection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Up Python 3
        uses: actions/setup-python@v1
        with: 
          python-version: '3.7'  

      # Set Up Connection to Dev Mongo
      # 1. Auth to cluster
      # 2. Open encrypted connection
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.DEV_CLOUDBUILD_SA_KEY }}
          project_id: ${{ secrets.DEV_PROJECT }}

      - name: Authenticate GHA Runner To Target Cluster
        run: gcloud container clusters get-credentials ${{secrets.DEV_GKE_CLUSTER}} --zone ${{secrets.DEV_GKE_REGION}} --project ${{secrets.DEV_GCP_PROJECT}}

      - name: Establish MongoDB Connection
        run: kubectl port-forward svc/mongo 27017:27017 &
      
      - name: Await MongoDB Connection
        run: sleep 20

      - name: Confirm MongoDB Connection
        # The following command returns a success code if mongo is available,
        # and a failure code if it is not
        run: curl localhost:27017

      - name: Establish PostgreSQL Connection
        run: kubectl port-forward svc/postgres 5432:5432 &

      - name: Await MongoDB Connection
        run: sleep 20

      - name: Confirm PostgreSQL Connection
        # if the PostgreSQL server is available, curl will fail with a '52' exit code
        # if it is NOT available, it will fail with a '7' exit code
        # run: curl localhost:5432; if [ $? -eq "52" ]; then exit 0; else exit 1; fi
        run: exitCode=$(curl localhost:5432; echo $?); if [ $exitCode -eq 52 ]; then exit 0; else exit 1; fi

      # - name: Install re2 # Find a way to avoid rebuilding constantly w/o using self-hosted runners

      - name: Install Python Packages
        run: |
          pip3 install django==1.11.* structlog
          pip3 install -r ./requirements.txt
      - name: Run Static Python Tests
        run: py.test -v -m 'not deep and not failing'
        continue-on-error: true
        timeout-minutes: 15
        env:
          DJANGO_SETTINGS_MODULE: "sefaria.settings"
          CI_RUN: "true"
...
