
# this will only handle static python and js tests
---
name: static-tests
on:
  - push
jobs:
  jest-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
          npm run build-prod
      - name: Run Jest Tests
        run: npm run jest-travis

  py-tests:
    # Requires an active mongodb connection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Up Python 3
        uses: actions/setup-python@v1
        with: 
          python-version: '3.7'  

      # Set Up Connection to Dev Mongo
      # 1. Auth to cluster
      # 2. Open encrypted connection
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.DEV_CLOUDBUILD_SA_KEY }}
          project_id: ${{ secrets.DEV_PROJECT }}

      - name: Authenticate GHA Runner To Target Cluster
        run: gcloud container clusters get-credentials ${{secrets.DEV_GKE_CLUSTER}} --zone ${{secrets.DEV_GKE_REGION}} --project ${{secrets.DEV_GCP_PROJECT}}

      - name: Establish MongoDB Connection
        run: 'kubectl port-forward svc/mongo 27017:27017 && sleep 20 &'
      #- name: Copy In local_settings.py

      - name: Install Python Packages
        run: |
          pip3 install django==1.11.* structlog --use-feature=2020-resolver
          pip3 install -r ./requirements.txt --use-feature=2020-resolver
      - name: Run Static Python Tests
        run: py.test -v -m 'not deep and not failing'
        env:
          DJANGO_SETTINGS_MODULE: "sefaria.settings"
...
