---
name: Weekly Tasks
on:
  schedule:
    - cron: '0 0 * 6 *'

jobs:
  build-mongo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.DEV_CLOUDBUILD_SA_KEY }}
      - name: Get current date
        id: date
        run: echo "date$(date +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT
      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            gcr.io/${{ secrets.DEV_PROJECT }}/sefaria-mongo
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha,enable=true,priority=100,prefix=sha-,suffix=-${{ steps.date.outputs.date }},format=short
            type=sha
          flavor: |
            latest=true
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry, ref=sefaria-mongo/cache
          cache-to: type=registry, ref=sefaria-mongo/cache, mode=max
          context: .
          push: true
          file: ./build/standalone-db/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
...
