---
name: Weekly Tasks
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cleanup-sandboxes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Authenticate GHA Runner to GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_BUILD_UPLOAD_KEY }}
          project_id: ${{ secrets.BUILD_UPLOAD_PROJECT }}

      - name: Trigger Cleanup Job
        run: gcloud builds submit --no-source --config ./build/ci/sandboxCleanup.yaml
...
